#!/usr/bin/env ruby
# This script outputs the `output.scss` section of a given path.
# It ignores all other arguments.
# The goal is to use this as an alternative for a full version of dart-sass
# for the purpose of unit testing sass-spec

# This script can be called two ways:
# 1. With the `-v` flag
# 2. With many flags where the second-to-last argument is a path to a HRX file.

require 'hrx'

# Version flag needs to return a value.
if ARGV.last == '-v'
  puts '0.1'
else
  path = ARGV[-2]
  puts HRX::Archive.load(path).read("output.css")
end
