#!/usr/bin/env ruby
# This program stubs out the Sass CLI. It does not apply any Sass
# transformations and simply outputs the input file to stdout.

# Version flag needs to return a value.
if ARGV.last == '-v'
  puts '0.1'
else
  puts ["input: #{ARGV.inspect}", "file: #{File.read(ARGV.last)}"].join("\n")
end
